Repository HiAvatar/backend, pull requests merged in 2022-10, with the labels that each got.

#23 fix: 배포 서버에서 S3 관련한 컴포넌트를 찾지 못하는 이슈 해결
  build.gradle
Labels: Type: Bug, Priority: Critical

#26 표준 시간을 한국에 맞게 설정
  src/main/java/com/fastcampus/finalproject/dto/AvatarPageDto.java
  src/main/java/com/fastcampus/finalproject/dto/response/GetHistoryResponse.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
  src/main/java/com/fastcampus/finalproject/util/CustomTimeUtil.java
Labels: Type: Bug, Priority: Critical

#27 feat: 서울 시간을 기준으로 적용되도록 코드 추가
  src/main/java/com/fastcampus/finalproject/entity/BaseTimeEntity.java
Labels: Type: Bug, Priority: Critical

#28 fix: LocalDateTime 대신 ZonedDateTime 사용
  src/main/java/com/fastcampus/finalproject/entity/BaseTimeEntity.java
  src/main/java/com/fastcampus/finalproject/util/CustomTimeUtil.java
Labels: Type: Bug

#29 fix: 한국 시간으로 변경하기 위해 auditing 코드 제거
  src/main/java/com/fastcampus/finalproject/FinalProjectApplication.java
  src/main/java/com/fastcampus/finalproject/entity/BaseTimeEntity.java
Labels: Priority: High

#33 feat: spring boot의 default timezone을 Asia/Seoul로 적용되도록 코드 추가
  src/main/java/com/fastcampus/finalproject/FinalProjectApplication.java
Labels: Priority: Medium

#38 fix: avatar 데이터가 순서대로 응답될 수 있도록 수정
  src/main/java/com/fastcampus/finalproject/dto/AvatarPageDto.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Priority: Critical

#40 refactor: api 명세서를 기반으로 메서드 순서 재배치 및 직관적인 메서드명으로 변경
  src/main/java/com/fastcampus/finalproject/controller/ProjectController.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Type: Maintenance, Priority: Medium

#45 feat: #44 텍스트 페이지에서 Script 입력 시 texts 컬럼에 저장
  src/main/java/com/fastcampus/finalproject/entity/Audio.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Type: Enhancement

#55 conf: http message body의 크기를 늘리는 설정 추가
  src/main/resources/application.yml
Labels: Priority: High

#59 fix: 음성 파일을 생성하면 기존의 음성 파일을 로컬에서 삭제되지 않는 버그 수정
  src/main/java/com/fastcampus/finalproject/aws/S3Uploader.java
Labels: Priority: Critical

#60 feat: #57 Project 가 존재하지 않을 때 예외 처리
  src/main/java/com/fastcampus/finalproject/controller/advice/ProjectControllerAdvice.java
  src/main/java/com/fastcampus/finalproject/dto/ErrorResponseWrapper.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Priority: Low

#70 아바타 선택 페이지에서 임시 저장 버튼 API 추가
  src/main/java/com/fastcampus/finalproject/controller/ProjectController.java
  src/main/java/com/fastcampus/finalproject/entity/Avatar.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Type: Enhancement

#75 fix: 데이터베이스에 한국 표준 시간이 적용되지 않는 버그 수정
  src/main/java/com/fastcampus/finalproject/FinalProjectApplication.java
  src/main/java/com/fastcampus/finalproject/entity/BaseTimeEntity.java
Labels: Priority: Critical

#74 영상 파일 생성 실패 및 특정 파일을 찾을 수 없을 때 예외처리
  src/main/java/com/fastcampus/finalproject/controller/advice/ProjectControllerAdvice.java
  src/main/java/com/fastcampus/finalproject/dto/ResponseWrapper.java
Labels: Priority: Low

#77 fix: FileNotFoundException으로 영상이 로컬 또는 s3에 저장되지 않음
  src/main/java/com/fastcampus/finalproject/controller/advice/ProjectControllerAdvice.java
Labels: Priority: Critical

#80 fix: 코드 수순 변경
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Priority: High

#94 fix: 텍스트 페이지에서 조회가 아닌 텍스트 페이지에서 음성 파일을 생성하기 전에 검증
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Type: Bug, Priority: Critical

#103 ProjectController에서 사용되는 resquest, response 클래스를 하나의 DTO 클래스로 리팩토링
  src/main/java/com/fastcampus/finalproject/controller/ProjectController.java
  src/main/java/com/fastcampus/finalproject/dto/ProjectHistoryDto.java
  src/main/java/com/fastcampus/finalproject/dto/TextPageDto.java
  src/main/java/com/fastcampus/finalproject/dto/request/AudioFileUploadRequest.java
  src/main/java/com/fastcampus/finalproject/dto/request/InsertTextPageRequest.java
  src/main/java/com/fastcampus/finalproject/dto/request/SentenceInputRequest.java
  src/main/java/com/fastcampus/finalproject/dto/request/TextInputRequest.java
  src/main/java/com/fastcampus/finalproject/dto/request/TotalAudioSyntheticRequest.java
  src/main/java/com/fastcampus/finalproject/dto/request/UpdateProjectNameRequest.java
  src/main/java/com/fastcampus/finalproject/dto/response/CreateProjectResponse.java
  src/main/java/com/fastcampus/finalproject/dto/response/GetHistoryResponse.java
  src/main/java/com/fastcampus/finalproject/dto/response/GetTextPageResponse.java
  src/main/java/com/fastcampus/finalproject/dto/response/InsertTextPageResponse.java
  src/main/java/com/fastcampus/finalproject/dto/response/SentenceInputResponse.java
  src/main/java/com/fastcampus/finalproject/dto/response/TextInputResponse.java
  src/main/java/com/fastcampus/finalproject/dto/response/TotalAudioSyntheticResponse.java
  src/main/java/com/fastcampus/finalproject/dto/response/UpdateProjectNameResponse.java
  src/main/java/com/fastcampus/finalproject/entity/Audio.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Priority: Low

#105 feat: 한 문장에 대한 오디오 파일을 생성할 때 로컬 파일에서 삭제시키는 기능 추가
  src/main/java/com/fastcampus/finalproject/aws/S3Uploader.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Priority: Critical

#107 feat: 프로젝트 texts 값이 미정일 경우 texts는 Blank, splitTextList는 EmptyList로 응답
  src/main/java/com/fastcampus/finalproject/dto/TextPageDto.java
Labels: Type: Enhancement, Priority: Critical

#109 ProjectService에서 userUid 없을 때 예외 처리
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Priority: Low

#113 ProjectService 리팩토링
  src/main/java/com/fastcampus/finalproject/dto/AudioDto.java
  src/main/java/com/fastcampus/finalproject/dto/TextPageDto.java
  src/main/java/com/fastcampus/finalproject/dto/VideoDto.java
  src/main/java/com/fastcampus/finalproject/entity/Video.java
  src/main/java/com/fastcampus/finalproject/enums/FlaskResponseType.java
  src/main/java/com/fastcampus/finalproject/service/FlaskService.java
  src/main/java/com/fastcampus/finalproject/service/ProjectService.java
Labels: Type: Maintenance, Priority: Low
